services:
  urlshortener:
    build: .
    ports:
      - "5050:5050"
      - "5051:5051"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5050;http://+:5051
    volumes:
      - ./app.db:/app/app.db
